# NumPy 演習: 2から18の偶数の行列を作ってみよう

NumPy を使って、**2から18までの偶数**を順番に並べた 3x3 の行列を作成してください。

### 行列（マトリックス）とは？
数字を格子状に並べたものです。NumPyでは、**「行」は横**の並び、**「列」は縦**の並びを指します。

```
    列1 列2 列3
行1 [2,  4,  6]
行2 [8, 10, 12]
行3 [14, 16, 18]
```

期待される出力:
```
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
```

## ヒント1: 数値の並びを作る
`np.arange(開始, 終了, ステップ)` を使うと、指定した間隔で数値の並びを作ることができます。

In [3]:
import numpy as np
# 2から20未満まで、2ずつ増える配列を作成
arr = np.arange(2, 20, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18]


## ヒント2: ブロードキャスト（便利な一括計算）
「1から9の配列」を作ってから、全体を2倍することでも同じ結果が得られます。
このように配列全体に一気に計算を適用することを**ブロードキャスト**と呼びます。

In [4]:
arr_base = np.arange(1, 10)
print("1-9の配列:", arr_base)
print("全体を2倍:", arr_base * 2)

1-9の配列: [1 2 3 4 5 6 7 8 9]
全体を2倍: [ 2  4  6  8 10 12 14 16 18]


## ヒント3: 行列にする
`.reshape(行, 列)` を使うと、1次元の配列を 3x3 の行列のような多次元の形に変換できます。

In [6]:
# 9個の要素を持つ1次元配列を 3x3 に変換する例
arr = np.arange(1, 10)
print("1-9の配列:", arr)
matrix = arr.reshape(3, 3)
print(matrix)

1-9の配列: [1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 解答欄
以下の欄にプログラムを作ってください

In [ ]:
import numpy as np